#!/usr/bin/env python3
"""
Extract frequency-response values from simulation outputs.

This script reads VTU files generated by frequency_sweep_solver.py, extracts
maximum displacement/pressure values and values at a user-defined target point,
then writes plots and a CSV table.

Default inputs
--------------
pressure_p0_*.vtu
displacement_p0_*.vtu

Default outputs
---------------
frequency_response_plot.png
target_point_response.png
target_response.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pyvista as pv


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot pressure and displacement frequency responses."
    )
    parser.add_argument("--start", type=float, default=10.0, help="First frequency in Hz.")
    parser.add_argument("--stop", type=float, default=1000.0, help="Last frequency in Hz.")
    parser.add_argument("--step", type=float, default=50.0, help="Frequency step in Hz.")
    parser.add_argument(
        "--target",
        type=float,
        nargs=3,
        default=(7.55542314, 17.2636752, 27.42938731),
        metavar=("X", "Y", "Z"),
        help="Target point coordinates for extracting local response.",
    )
    parser.add_argument(
        "--pressure-pattern",
        default="pressure_p0_{idx:06d}.vtu",
        help="Filename pattern for pressure files.",
    )
    parser.add_argument(
        "--displacement-pattern",
        default="displacement_p0_{idx:06d}.vtu",
        help="Filename pattern for displacement files.",
    )
    return parser.parse_args()


def closest_point_index(points: np.ndarray, target: np.ndarray) -> int:
    distances = np.linalg.norm(points - target, axis=1)
    return int(np.argmin(distances))


def get_scalar_field(grid: pv.DataSet, candidate_names: list[str]) -> np.ndarray:
    for name in candidate_names:
        if name in grid.point_data:
            return np.asarray(grid.point_data[name])
    raise KeyError(f"None of the expected fields were found: {candidate_names}")


def get_vector_field(grid: pv.DataSet, candidate_names: list[str]) -> np.ndarray:
    for name in candidate_names:
        if name in grid.point_data:
            values = np.asarray(grid.point_data[name])
            if values.ndim == 2:
                return values
    raise KeyError(f"None of the expected vector fields were found: {candidate_names}")


def read_pressure(grid: pv.DataSet) -> np.ndarray:
    real = get_scalar_field(grid, ["acoustic_pressure_real", "f_real", "pressure_real"])
    if "acoustic_pressure_imag" in grid.point_data:
        imag = np.asarray(grid.point_data["acoustic_pressure_imag"])
        return np.sqrt(real**2 + imag**2)
    if "f_imag" in grid.point_data:
        imag = np.asarray(grid.point_data["f_imag"])
        return np.sqrt(real**2 + imag**2)
    return np.abs(real)


def read_displacement(grid: pv.DataSet) -> np.ndarray:
    real = get_vector_field(grid, ["f_real", "displacement_real", "displacement"])
    if "f_imag" in grid.point_data:
        imag = np.asarray(grid.point_data["f_imag"])
        return np.sqrt(np.sum(real**2 + imag**2, axis=1))
    if "displacement_imag" in grid.point_data:
        imag = np.asarray(grid.point_data["displacement_imag"])
        return np.sqrt(np.sum(real**2 + imag**2, axis=1))
    return np.linalg.norm(real, axis=1)


def main() -> None:
    args = parse_args()

    frequencies = np.arange(args.start, args.stop + 0.5 * args.step, args.step)
    target = np.array(args.target, dtype=float)

    pressure_max: list[float] = []
    displacement_max: list[float] = []
    pressure_at_target: list[float] = []
    displacement_at_target: list[float] = []

    for idx, frequency in enumerate(frequencies):
        pressure_file = Path(args.pressure_pattern.format(idx=idx, frequency=frequency))
        displacement_file = Path(args.displacement_pattern.format(idx=idx, frequency=frequency))

        if not pressure_file.exists() or not displacement_file.exists():
            print(f"Missing files for {frequency:g} Hz: {pressure_file}, {displacement_file}")
            pressure_max.append(np.nan)
            displacement_max.append(np.nan)
            pressure_at_target.append(np.nan)
            displacement_at_target.append(np.nan)
            continue

        pressure_grid = pv.read(pressure_file)
        displacement_grid = pv.read(displacement_file)

        pressure_values = read_pressure(pressure_grid)
        displacement_values = read_displacement(displacement_grid)

        p_index = closest_point_index(pressure_grid.points, target)
        u_index = closest_point_index(displacement_grid.points, target)

        pressure_max.append(float(np.nanmax(pressure_values)))
        displacement_max.append(float(np.nanmax(displacement_values)))
        pressure_at_target.append(float(pressure_values[p_index]))
        displacement_at_target.append(float(displacement_values[u_index]))

        print(
            f"{frequency:g} Hz: "
            f"P_target={pressure_at_target[-1]:.3e}, "
            f"U_target={displacement_at_target[-1]:.3e}"
        )

    data = np.column_stack(
        [
            frequencies,
            pressure_max,
            displacement_max,
            pressure_at_target,
            displacement_at_target,
        ]
    )
    header = (
        "frequency_hz,pressure_max,displacement_max,"
        "pressure_at_target,displacement_at_target"
    )
    np.savetxt("target_response.csv", data, delimiter=",", header=header, comments="")

    fig, ax1 = plt.subplots()
    ax1.set_xlabel("Frequency [Hz]")
    ax1.set_ylabel("Maximum acoustic pressure [Pa]")
    ax1.plot(frequencies, pressure_max, "o-")

    ax2 = ax1.twinx()
    ax2.set_ylabel("Maximum displacement [m]")
    ax2.plot(frequencies, displacement_max, "s--")

    fig.tight_layout()
    plt.savefig("frequency_response_plot.png", dpi=300)
    plt.close(fig)

    fig, ax1 = plt.subplots()
    ax1.set_xlabel("Frequency [Hz]")
    ax1.set_ylabel("Acoustic pressure at target [Pa]")
    ax1.plot(frequencies, pressure_at_target, "o-")

    ax2 = ax1.twinx()
    ax2.set_ylabel("Displacement at target [m]")
    ax2.plot(frequencies, displacement_at_target, "s--")

    fig.tight_layout()
    plt.savefig("target_point_response.png", dpi=300)
    plt.close(fig)

    print("Wrote target_response.csv")
    print("Wrote frequency_response_plot.png")
    print("Wrote target_point_response.png")


if __name__ == "__main__":
    main()
